# Generated by Django 5.2.9 on 2025-12-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentbooking',
            name='is_returned',
        ),
        migrations.AddField(
            model_name='rentbooking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending Approval'), ('Approved', 'Approved'), ('Shipped', 'Shipped / On Way'), ('Active', 'Active / Delivered'), ('Returned', 'Returned'), ('Overdue', 'Overdue'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
