# Generated by Django 5.2.9 on 2025-12-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_rentbooking_status_alter_saleorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_rentable',
            field=models.BooleanField(default=False, verbose_name='Available for Rent'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
