# Generated by Django 5.2.9 on 2025-12-25 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_deliveryboy_order_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentbooking',
            name='parent_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rent_items', to='shop.order'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='parent_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_items', to='shop.order'),
        ),
    ]
