# Generated by Django 5.2.9 on 2025-12-27 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_rentbooking_parent_order_saleorder_parent_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryboy',
            name='phone',
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliveryboy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='deliveryboy',
            name='vehicle_type',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
