# Generated by Django 5.2.9 on 2025-12-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_deliveryboy_phone_alter_deliveryboy_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentbooking',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rentbooking',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
