# Generated by Django 5.2.9 on 2025-12-29 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='otp',
        ),
        migrations.AddField(
            model_name='delivery',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
